CrescentCoffee/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace CrescentCoffee.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CrescentCoffee/Controllers/CoffeeController.cs
using CrescentCoffee.Models;
using CrescentCoffee.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.Dynamic;

namespace CrescentCoffee.Controllers
{
    public class CoffeeController : Controller
    {
        private readonly ICoffeeRepository _coffeeRepository;
        private readonly ICoffeeTypeRepository _coffeeTypeRepository;

        public CoffeeController
            (ICoffeeRepository coffeeRepository, ICoffeeTypeRepository coffeeTypeRepository)
        {
            _coffeeRepository = coffeeRepository;
            _coffeeTypeRepository = coffeeTypeRepository;
        }

        public ViewResult CoffeeList(string coffeeType)
        {
            IEnumerable<Coffee> coffees;
            string? currentCoffeeType;

            if (string.IsNullOrEmpty(coffeeType) || 
                (_coffeeRepository.AllCoffees.Where(c => c.CoffeeType.Type.Equals(coffeeType)).IsNullOrEmpty() && !coffeeType.IsNullOrEmpty()))
            {
                coffees = _coffeeRepository.AllCoffees.OrderBy(c => c.CoffeeId);
                currentCoffeeType = "All Coffees";
            }
            else
            {
                coffees = _coffeeRepository.AllCoffees.Where(c => c.CoffeeType.Type.Equals(coffeeType)).OrderBy(c => c.CoffeeId);
                currentCoffeeType = _coffeeTypeRepository.AllCoffeeTypes.FirstOrDefault(c => c.Type.Equals(coffeeType))?.Type;
            }

            return View(new CoffeeListViewModel(coffees, currentCoffeeType));
        }

        public IActionResult Details(int id)
        {
            dynamic mymodel = new ExpandoObject();

            var coffee = _coffeeRepository.GetCoffeeById(id);
            if (coffee == null)
            {
                return NotFound();
            }

            mymodel.Coffee = coffee;
            mymodel.CoffeeType = _coffeeTypeRepository.AllCoffeeTypes.FirstOrDefault(t => t.CoffeeTypeId.Equals(coffee.CoffeeTypeId));

            var test = mymodel.Coffee;

            return View(mymodel);
        }

        public IActionResult Search()
        {
            return View();
        }
    }
}

CrescentCoffee/Views/Shared/_Carousel.cshtml
<div id="carouselImages" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner" style="border-radius:5px">
        <div class="carousel-item active">
            <img src="~/Images/carousel1.jpg" class="d-block w-100" alt="Carousel image 1">
        </div>
        <div class="carousel-item">
            <img src="~/Images/carousel2.jpg" class="d-block w-100" alt="Carousel image 2">
        </div>
        <div class="carousel-item">
            <img src="~/Images/carousel3.jpg" class="d-block w-100" alt="Carousel image 3">
        </div>
    </div>
</div>

CrescentCoffee/Views/Shared/_CarouselAbout.cshtml
<div id="carouselImages2" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselImages2" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselImages2" data-bs-slide-to="1" aria-label="Slide 2"></button>
    </div>
    <div class="carousel-inner" style="border-radius:5px">
        <div class="carousel-item active">
            <img src="~/Images/truck.jpg" class="d-block w-100" alt="Carousel image 1">
        </div>
        <div class="carousel-item">
            <img src="~/Images/truck2.jpg" class="d-block w-100" alt="Carousel image 2">
        </div>
    </div>
</div>

CrescentCoffee/Views/Shared/_CoffeeCard.cshtml
@model Coffee

<div class="col">
    <div class="card coffee-card">
        <img src="~/@Model.ImageThumbnailPath" class="card-img-top" alt="@Model.Name" style="background-color: #ece0d1">
        <div class="card-body coffee-button">
                @if (Model.InStock)
                {
                    <h4 class="d-grid">
                    <button class="btn-link" onclick=AddItem(@Model.CoffeeId)> + Add to cart</button>
                    </h4>
                }
                else
                {
                    <h4>
                        Out of Stock :(
                    </h4>
                }
            

            <div class="d-flex justify-content-between mt-2">
                <h2 class="text-start">
                    <a asp-controller="Coffee"
                    asp-action="Details"
                    asp-route-id="@Model.CoffeeId"
                    class="coffee-link">@Model.Name</a>
                </h2>
                <h5 class="text-nowrap">
                    @Model.Price.ToString("c")
                </h5>
            </div>
            <div>
                <h3 class="text-nowrap">
                    @Model.Size
                </h3>
                <h3 class="text-nowrap">
                    @ViewBag.Message
                </h3>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function AddItem(id) {
        $.ajax({
            url: '/ShoppingCart/AddToShoppingCart',
            data: "coffeeId=" + id,
            success: function() {
                location.reload();
            }
        });
    }
</script>

CrescentCoffee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Crescent Coffee</title>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans' rel='stylesheet' type='text/css'>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <base href="/" />
</head>
<body>
    <div class="container">
        <div class="content-wrap">
            <header>
                <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary"
                     aria-label="Crescent Coffee navigation header">
                    <div class="container-xl">
                        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                            <img src="images/logo-white-small.png" width="200" height="51" class="d-inline-block align-top mb-2 mt-1"
                                 alt="Crescent Coffee Logo">
                        </a>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarCollapse">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <vc:coffee-type-menu></vc:coffee-type-menu>
                                <li class="nav-item">
                                    <a asp-controller="About" asp-action="Index" class="nav-link">About</a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Contact" asp-action="Index" class="nav-link">Contact</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Coffee" asp-action="Search">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                                        </svg>
                                    </a>
                                </li>
                            </ul>
                            <vc:shopping-cart-summary></vc:shopping-cart-summary>
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </nav>
            </header>
        <main>
            @RenderBody()
            @RenderSection("Scripts", required: false)
            @* <script src="_framework/blazor.web.js"></script>  *@
            </main>
        </div>
    </div>
    <footer class="footer">
        <div class="footer-container-main">
            <a class="button footer-left" href="#top" onclick="scroll(0,0)" style="font-size: 14px">
                <img src="images/crescent-logo-black-2-smaller.png" width="100" height="25" alt="Crescent Coffee Logo">
            </a>
            <partial name="_Social" />
        </div>
        <div class="copyright" style="font-size: 9px">
            <p style="margin:5px">2025 &copy Crescent Coffee&trade;</p>
        </div>
    </footer>
</body>
</html>